# Generated by Django 6.0.2 on 2026-04-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_otprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
