# Generated by Django 6.0.2 on 2026-04-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipeent',
            new_name='recipient',
        ),
    ]
