# Generated by Django 6.0.2 on 2026-08-07 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0005_rename_recipeent_notification_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('LOGIN_SUCESS', 'successful login'), ('LOGIN_FAILED', 'failed login attempt'), ('LOGIN_SUCESS', 'user logout')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-time_stamp'],
            },
        ),
    ]
