# Generated by Django 6.0.2 on 2026-08-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterprofile',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HunterEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='guild.hunterprofile')),
                ('task_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='guild.taskassignment')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('razorpay_idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawls', to='guild.hunterprofile')),
            ],
        ),
    ]
