upstream django_web {
    # This points to the 'web' service in docker-compose on port 8000
    server web:8000;
}

server {
    listen 80;

    # Route 1: Any standard request goes to Gunicorn/Django
    location / {
        proxy_pass http://django_web;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Route 2: Nginx serves static files directly (super fast)
    location /static/ {
        alias /app/static/;
    }

    # Route 3: Nginx serves uploaded images/proofs directly
    location /media/ {
        alias /app/media/;
    }
}